[package]
name = "barber-shop-simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["alloc"] }
derive_more = "0.99"
sorted-vec = "0.8"
rand = "0.8"
